DROP DATABASE IF EXISTS DB_TCCGrupo3;

CREATE DATABASE DB_TCCGrupo3;
USE DB_TCCGrupo3;

CREATE TABLE USUARIO (
    IDUSUARIO INT NOT NULL PRIMARY KEY AUTO_INCREMENT
    , NOME VARCHAR(100)
    , EMAIL VARCHAR(100)
    , SENHA VARCHAR(45)
);